# Generated by Django 4.1.10 on 2023-08-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='users',
            field=models.ManyToManyField(to='accounts.customuser'),
        ),
    ]
